"""
Locust load test for notification_routes.py
File: LoadTests/locustfile_notifications.py

Run from project root:
    locust -f LoadTests/locustfile_notifications.py --host=http://localhost:5000

Then open http://localhost:8089 in your browser.

Or headless:
    locust -f LoadTests/locustfile_notifications.py \
           --host=http://localhost:5000 \
           --headless -u 50 -r 5 --run-time 2m
"""

import random
import string
from bson import ObjectId

from locust import HttpUser, TaskSet, between, task, events


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _random_email(prefix="locust"):
    suffix = "".join(random.choices(string.ascii_lowercase + string.digits, k=8))
    return f"{prefix}_{suffix}@loadtest.com"


def _register_and_login(client, role="recruiter"):
    """Register a fresh user and return a Bearer auth header dict."""
    email = _random_email(role)
    client.post(
        "/api/auth/register",
        json={
            "first_name": "Load",
            "last_name":  "Tester",
            "email":      email,
            "password":   "Test@1234",
            "role":       role,
        },
        name="/api/auth/register [setup]",
    )
    res = client.post(
        "/api/auth/login",
        json={"email": email, "password": "Test@1234"},
        name="/api/auth/login [setup]",
    )
    token = res.json().get("access_token", "")
    return {"Authorization": f"Bearer {token}"}


def _create_notification(client, headers, payload=None):
    payload = payload or {
        "type":    "new_candidate",
        "title":   "Load-test Notification",
        "message": "Generated by Locust",
    }
    res = client.post(
        "/api/notifications/",
        json=payload,
        headers=headers,
        name="POST /api/notifications/",
    )
    if res.status_code == 201:
        return res.json().get("data", {}).get("_id")
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Task sets — grouped by endpoint
# ─────────────────────────────────────────────────────────────────────────────

class GetNotificationsTaskSet(TaskSet):
    """
    Exercises GET /api/notifications/ with various query strings.
    """

    @task(5)
    def get_all_notifications(self):
        self.client.get(
            "/api/notifications/",
            headers=self.user.auth_headers,
            name="GET /api/notifications/",
        )

    @task(3)
    def get_notifications_with_limit(self):
        limit = random.choice([5, 10, 20, 50])
        self.client.get(
            f"/api/notifications/?limit={limit}",
            headers=self.user.auth_headers,
            name="GET /api/notifications/?limit=N",
        )

    @task(1)
    def get_notifications_no_auth(self):
        """Expect 401 — validates the auth guard under load."""
        with self.client.get(
            "/api/notifications/",
            name="GET /api/notifications/ [no auth]",
            catch_response=True,
        ) as res:
            if res.status_code == 401:
                res.success()
            else:
                res.failure(f"Expected 401, got {res.status_code}")


class CreateNotificationTaskSet(TaskSet):
    """
    Exercises POST /api/notifications/.
    """

    TYPES = ["new_candidate", "placement", "system", "warning", "job_update", "onboarding"]
    TARGET_ROLES = ["recruiter", "hr", "manager", None]

    @task(6)
    def create_valid_notification(self):
        payload = {
            "type":  random.choice(self.TYPES),
            "title": f"Locust notif {random.randint(1000, 9999)}",
        }
        target_role = random.choice(self.TARGET_ROLES)
        if target_role:
            payload["target_role"] = target_role
        self.client.post(
            "/api/notifications/",
            json=payload,
            headers=self.user.auth_headers,
            name="POST /api/notifications/ [valid]",
        )

    @task(2)
    def create_notification_with_message(self):
        payload = {
            "type":    "system",
            "title":   "System alert",
            "message": "This is a load-test message body.",
        }
        self.client.post(
            "/api/notifications/",
            json=payload,
            headers=self.user.auth_headers,
            name="POST /api/notifications/ [with message]",
        )

    @task(1)
    def create_notification_with_target_user(self):
        payload = {
            "type":           "job_update",
            "title":          "Job updated",
            "target_user_id": f"user_{random.randint(1, 999)}",
        }
        self.client.post(
            "/api/notifications/",
            json=payload,
            headers=self.user.auth_headers,
            name="POST /api/notifications/ [target_user]",
        )

    @task(1)
    def create_notification_missing_type(self):
        """Expect 400 — validates validation under load."""
        with self.client.post(
            "/api/notifications/",
            json={"title": "No type"},
            headers=self.user.auth_headers,
            name="POST /api/notifications/ [missing type → 400]",
            catch_response=True,
        ) as res:
            if res.status_code == 400:
                res.success()
            else:
                res.failure(f"Expected 400, got {res.status_code}")

    @task(1)
    def create_notification_no_auth(self):
        """Expect 401."""
        with self.client.post(
            "/api/notifications/",
            json={"type": "system", "title": "Unauth"},
            name="POST /api/notifications/ [no auth → 401]",
            catch_response=True,
        ) as res:
            if res.status_code == 401:
                res.success()
            else:
                res.failure(f"Expected 401, got {res.status_code}")


class MarkReadTaskSet(TaskSet):
    """
    Exercises PUT /api/notifications/<id>/read.
    Creates a notification first, then marks it read.
    """

    @task(5)
    def mark_notification_read(self):
        nid = _create_notification(self.client, self.user.auth_headers)
        if not nid:
            return
        self.client.put(
            f"/api/notifications/{nid}/read",
            headers=self.user.auth_headers,
            name="PUT /api/notifications/<id>/read [valid]",
        )

    @task(2)
    def mark_read_idempotent(self):
        """Mark same notification read twice."""
        nid = _create_notification(self.client, self.user.auth_headers)
        if not nid:
            return
        for _ in range(2):
            self.client.put(
                f"/api/notifications/{nid}/read",
                headers=self.user.auth_headers,
                name="PUT /api/notifications/<id>/read [idempotent]",
            )

    @task(1)
    def mark_read_unknown_id(self):
        """PUT with a valid-format but non-existent ObjectId — should 200."""
        fake = str(ObjectId())
        self.client.put(
            f"/api/notifications/{fake}/read",
            headers=self.user.auth_headers,
            name="PUT /api/notifications/<id>/read [unknown id]",
        )

    @task(1)
    def mark_read_invalid_id(self):
        """Expect 400."""
        with self.client.put(
            "/api/notifications/NOT_AN_OID/read",
            headers=self.user.auth_headers,
            name="PUT /api/notifications/<id>/read [bad id → 400]",
            catch_response=True,
        ) as res:
            if res.status_code == 400:
                res.success()
            else:
                res.failure(f"Expected 400, got {res.status_code}")

    @task(1)
    def mark_read_no_auth(self):
        """Expect 401."""
        fake = str(ObjectId())
        with self.client.put(
            f"/api/notifications/{fake}/read",
            name="PUT /api/notifications/<id>/read [no auth → 401]",
            catch_response=True,
        ) as res:
            if res.status_code == 401:
                res.success()
            else:
                res.failure(f"Expected 401, got {res.status_code}")


class MarkAllReadTaskSet(TaskSet):
    """
    Exercises PUT /api/notifications/read-all.
    """

    @task(5)
    def mark_all_read(self):
        # Seed a couple of notifications first
        for _ in range(2):
            _create_notification(self.client, self.user.auth_headers)
        self.client.put(
            "/api/notifications/read-all",
            headers=self.user.auth_headers,
            name="PUT /api/notifications/read-all",
        )

    @task(1)
    def mark_all_read_no_auth(self):
        """Expect 401."""
        with self.client.put(
            "/api/notifications/read-all",
            name="PUT /api/notifications/read-all [no auth → 401]",
            catch_response=True,
        ) as res:
            if res.status_code == 401:
                res.success()
            else:
                res.failure(f"Expected 401, got {res.status_code}")


class DeleteNotificationTaskSet(TaskSet):
    """
    Exercises DELETE /api/notifications/<id>.
    """

    @task(5)
    def delete_notification(self):
        nid = _create_notification(self.client, self.user.auth_headers)
        if not nid:
            return
        self.client.delete(
            f"/api/notifications/{nid}",
            headers=self.user.auth_headers,
            name="DELETE /api/notifications/<id> [valid]",
        )

    @task(2)
    def delete_idempotent(self):
        """Delete same notification twice."""
        nid = _create_notification(self.client, self.user.auth_headers)
        if not nid:
            return
        for _ in range(2):
            self.client.delete(
                f"/api/notifications/{nid}",
                headers=self.user.auth_headers,
                name="DELETE /api/notifications/<id> [idempotent]",
            )

    @task(1)
    def delete_unknown_id(self):
        """DELETE non-existent ObjectId — should 200."""
        fake = str(ObjectId())
        self.client.delete(
            f"/api/notifications/{fake}",
            headers=self.user.auth_headers,
            name="DELETE /api/notifications/<id> [unknown id]",
        )

    @task(1)
    def delete_invalid_id(self):
        """Expect 400."""
        with self.client.delete(
            "/api/notifications/BAD_ID",
            headers=self.user.auth_headers,
            name="DELETE /api/notifications/<id> [bad id → 400]",
            catch_response=True,
        ) as res:
            if res.status_code == 400:
                res.success()
            else:
                res.failure(f"Expected 400, got {res.status_code}")

    @task(1)
    def delete_no_auth(self):
        """Expect 401."""
        fake = str(ObjectId())
        with self.client.delete(
            f"/api/notifications/{fake}",
            name="DELETE /api/notifications/<id> [no auth → 401]",
            catch_response=True,
        ) as res:
            if res.status_code == 401:
                res.success()
            else:
                res.failure(f"Expected 401, got {res.status_code}")


# ─────────────────────────────────────────────────────────────────────────────
# Mixed end-to-end task set (realistic user journey)
# ─────────────────────────────────────────────────────────────────────────────

class NotificationJourneyTaskSet(TaskSet):
    """
    Simulates a realistic user session:
      1. List notifications
      2. Create one
      3. Mark it read
      4. List again
      5. Occasionally delete or mark-all-read
    """

    def on_start(self):
        self._last_nid = None

    @task(4)
    def list_notifications(self):
        if not hasattr(self.user, 'auth_headers'):
            return
        self.client.get(
            "/api/notifications/",
            headers=self.user.auth_headers,
            name="GET /api/notifications/ [journey]",
        )

    @task(3)
    def create_and_read(self):
        nid = _create_notification(self.client, self.user.auth_headers,
                                   payload={
                                       "type":  random.choice(["new_candidate", "system", "warning"]),
                                       "title": f"Journey notif {random.randint(1, 9999)}",
                                   })
        if nid:
            self._last_nid = nid
            self.client.put(
                f"/api/notifications/{nid}/read",
                headers=self.user.auth_headers,
                name="PUT /api/notifications/<id>/read [journey]",
            )

    @task(1)
    def mark_all_read(self):
        self.client.put(
            "/api/notifications/read-all",
            headers=self.user.auth_headers,
            name="PUT /api/notifications/read-all [journey]",
        )

    @task(1)
    def delete_last(self):
        if self._last_nid:
            self.client.delete(
                f"/api/notifications/{self._last_nid}",
                headers=self.user.auth_headers,
                name="DELETE /api/notifications/<id> [journey]",
            )
            self._last_nid = None


# ─────────────────────────────────────────────────────────────────────────────
# User classes
# ─────────────────────────────────────────────────────────────────────────────

class AdminNotificationUser(HttpUser):
    """
    Admin user: hits all endpoints with higher concurrency.
    Weight 2 → spawned twice as often as other roles.
    """
    weight      = 2
    wait_time   = between(0.5, 2)
    tasks       = {
        GetNotificationsTaskSet:   5,
        CreateNotificationTaskSet: 4,
        MarkReadTaskSet:           3,
        MarkAllReadTaskSet:        2,
        DeleteNotificationTaskSet: 2,
        NotificationJourneyTaskSet: 4,
    }

    def on_start(self):
        self.auth_headers = _register_and_login(self.client, role="admin")


class RecruiterNotificationUser(HttpUser):
    """
    Recruiter: reads and creates notifications; no admin-only operations.
    """
    weight    = 3
    wait_time = between(1, 3)
    tasks     = {
        GetNotificationsTaskSet:    6,
        CreateNotificationTaskSet:  3,
        MarkReadTaskSet:            3,
        MarkAllReadTaskSet:         1,
        NotificationJourneyTaskSet: 5,
    }

    def on_start(self):
        self.auth_headers = _register_and_login(self.client, role="recruiter")


class HRNotificationUser(HttpUser):
    """
    HR user: focuses on reading and marking read.
    """
    weight    = 2
    wait_time = between(1, 4)
    tasks     = {
        GetNotificationsTaskSet: 8,
        MarkReadTaskSet:         4,
        MarkAllReadTaskSet:      2,
        NotificationJourneyTaskSet: 3,
    }

    def on_start(self):
        self.auth_headers = _register_and_login(self.client, role="hr")


class ManagerNotificationUser(HttpUser):
    """
    Manager: balanced read/create/delete mix.
    """
    weight    = 1
    wait_time = between(2, 5)
    tasks     = {
        GetNotificationsTaskSet:    5,
        CreateNotificationTaskSet:  2,
        MarkReadTaskSet:            3,
        DeleteNotificationTaskSet:  2,
        NotificationJourneyTaskSet: 3,
    }

    def on_start(self):
        self.auth_headers = _register_and_login(self.client, role="manager")